# Generated by Django 2.0.1 on 2018-08-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
